### PR TITLE
#1836 Stat Con - Enhancements

### LINKED ISSUE #1836: Stat Con - Onscreen Enchancements
As a user in JAC and JO I need a report that is fit for use in the Stat Con process. The current manual process of pulling information from several sources into a word doc is time consuming and the wrong format for JO. JO then have to take the word doc and convert this into excel document to sent out to stakeholders.

The following needs to be add to complete the onscreen visuals for a candidate:

- [x] List all candidates in alphabetical order
- [x] Add pagination
- [x] Add a search box at the top
- [x] Filter by stage and status
- [x] Ability to view application via a link - similar to RAs and Character
- [x] Text box to record any comments which are saved on the platform

### PR DESCRIPTION
**Pull request by HalcyonJAC**
## What's included?
Closes #1836 

The following will be implemented:
- [x]  List all candidates (invited to Selection Day) in alphabetical order
- [x]  Add pagination
- [x]  Add a search box at the top (dummy candidates will not show)
- [x]  Ability to view application via a link
- [x]  Text box to record any comments which are saved on the platform

## Who should test?
✅ Product owner
✅ Developers
✅ UTG

## How to test?
Go to Statutory Consultation Report and check if the above items work.

## Risk - how likely is this to impact other areas?
🟢 No risk - this is a self-contained piece of work

## Additional context
Screenshot:

Screenshot 2023-03-06 at 11 27 22

## Related permissions
Have permissions been considered for this functionality?
- No permission changes required

---
PREVIEW:DEVELOP
_can be OFF, DEVELOP or STAGING_

### CODE REVIEW

File: src/views/Exercise/Reports/StatutoryConsultation.vue [hunk 1]
```diff
@@ -38,21 +38,89 @@
...
+          </template>
+        </Table>
+
+        <button
+          class="govuk-button govuk-button--secondary moj-button-menu__item moj-page-header-actions__action govuk-!-margin-top-2"
+          @click="togglePagination"
+        >
+          {{ paginationType === 'uppercase-letter' ? '1 2 3 4' : 'A B C D' }}
+        </button>
+      </div>
```
Comment (warrensearle) [inline src/views/Exercise/Reports/StatutoryConsultation.vue:87]: So we don't end up with lots of copies of the same code could the toggle pagination functionality be moved to within the Table component?

Comment (HalcyonJAC) [reply src/views/Exercise/Reports/StatutoryConsultation.vue:87]: @warrensearle Good suggestion. I will create another PR in jac-kit to update the Table component.

**Review by andrew-isaac — APPROVED** [review]

**Review by warrensearle — APPROVED** [review]

**Review by tomlovesgithub — APPROVED** [review]
