### PR TITLE
#2165 Bug: Exercise. Eligibility Information. ASC word limit messaging is illogical

### LINKED ISSUE #2165: Bug: Exercise. Eligibility Information. ASC word limit messaging is illogical
In Exercise > Eligibility Information the Additional Selection Criteria can be configured to have a word limit. The label/hint for the word limit field suggests if the field is left empty then the word limit will default to 250. However the field is required which doesn't match up with the labelling.

Here's an image of the field when the form is submitted with no value:
image

**Actual**
Messaging suggests entering a value is optional however validation requires a value to have been entered.

**Expected**
Messaging and validation should make sense. Either:

 - Messaging remains as is and validation does not require a value to have been entered (i.e. field is optional)

Or:

 - Messaging remains as is. The field value defaults to 250 when the exercise is created and also if the user empties the field.

[ @nickaddy please confirm the behavior you'd prefer ]

### PR DESCRIPTION
**Pull request by drieJAC**
## What's included?
Ensure the field specifying the word limit is not a required field and the default word limit applies when not filled in.

Closes #2165 

## Who should test?
✅ Product owner
✅ Developers
✅ UTG

## How to test?

**There is a video attached below which shows the whole testing process!**

Test 1:
- Go to the following page (you may need to login first): https://jac-admin-develop--pr2218-feature-2165-asc-wor-srzka530.web.app/exercise/Vulmahzn4VtelQhVlJy6/details/overview
- You may need to unlock the exercise for editing
- Go to the Eligibility Information section and press 'Update eligibility information'
- Scroll down to the section which says: Does additional selection criteria (ASC) apply?
- Select 'No' and then 'Save And Continue'. If there are any errors just click the 'Save And Continue Anyway' button

Test 2
- At the top of the page click 'Update eligibility information'
- Scroll down to the section which says: Does additional selection criteria (ASC) apply?
- Select 'Yes'
- Add a title and text **but no word limit**
- Click the button to 'add another'
- Add a title and text **and specify a word limit of 10**
- Click 'Save And Continue'. If there are any errors just click the 'Save And Continue Anyway' button

Test 3
- At the top of the page click 'Update eligibility information'
- Scroll down to the section which says: Does additional selection criteria (ASC) apply?
- Ensure the titles/text/word counts are as entered in the previous test

**Now you can approve and publish the exercise then go to the Apply site and follow the instructions in this pull request:** 

## Risk - how likely is this to impact other areas?
🟢 No risk - this is a self-contained piece of work

## Additional context

https://github.com/jac-uk/admin/assets/115651787/11be1b8c-bb71-4f52-b920-987cc618b306

---
PREVIEW:DEVELOP
_can be OFF, DEVELOP or STAGING_

### CODE REVIEW

**Review by Franceswog — COMMENTED** [review]
The entire test was carried out and works as expected including the exercise on 'apply'

File: src/components/RepeatableFields/SelectionCriterion.vue [hunk 1]
```diff
@@ -32,13 +32,15 @@
...
 import RichTextInput from '@jac-uk/jac-kit/draftComponents/Form/RichTextInput.vue';
+import { shallowRef } from 'vue';
 
 export default {
   name: 'SelectionCriterion',
   components: {
     TextField,
     RichTextInput,
   },
+  inject: ['defaultWordLimit'],
```
Comment (HalcyonJAC) [inline src/components/RepeatableFields/SelectionCriterion.vue:43]: Nice to see `provide/inject` pattern 👍

**Review by HalcyonJAC — APPROVED** [review]

**Review by warrensearle — APPROVED** [review]
Code looks good to me 👍

**Review by Franceswog — APPROVED** [review]
