### PR TITLE
Bugfix/include all candidates in merit list 2

### LINKED ISSUE #2668: Include ALL candidates in QT Merit list
## Describe the bug
Candidates who take the SJT but not the CAT - or vice versa - are missing from the QT Merit list download, e.g. these two candidates on JAC00227: [JAC00227-hpd0466](https://admin.judicialappointments.digital/exercise/cEe3G1EdDwyFZjUdKgA2/applications/applied/application/IGgJGXJpah49qMOlHSkB), [JAC00227-rnf0142](https://admin.judicialappointments.digital/exercise/cEe3G1EdDwyFZjUdKgA2/applications/applied/application/xyahErVqXws7Jx8SNJhj).

In addition, **in the merit list download**, some withdrawn candidates are appearing ((JAC00227-nla0077, JAC00227-nla0077) but one withdrawn candidate (JAC00227-bda0120) is not included. We would like to include withdrawn candidates at the end of the list. In their case, the status column should show 'Withdrew'.

## To Reproduce
Steps to reproduce the behaviour:
1. Go to the [227 QT merit list task](https://admin.judicialappointments.digital/exercise/cEe3G1EdDwyFZjUdKgA2/tasks/all/qualifyingTest/finalised/) and try to find the above two candidates in the list
2. Check their status etc in relation to the tests taken on QT Admin

## Expected behaviour
All candidates who took CAT only, SJT only and both tests should be included in the QT merit list, even if they are automatically failed/withdrew.

### PR DESCRIPTION
**Pull request by KoWeiJAC**
## What's included?
Closes #2668 

## Who should test?
✅ Product owner
✅ Developers
✅ UTG

## How to test?
- Go to the preview link: https://jac-admin-develop--pr2706-bugfix-include-all-c-10sq1zz3.web.app/exercise/pvP1C5XCCfPTZZNFAPGu/tasks/all/qualifyingTest/finalised/
- Check the all candidates are in the merit list download
    -  Includes candidates taking any one of CAT(Critical Analysis Test) and SJT(Situational Judgement Test)
    -  Includes withdrawn candidates
- Go to the preview link: https://admin-develop.judicialappointments.digital/exercise/QWXzmysQXBzpAngOGz7a/tasks/all/selectionDay/finalised/
- Check the all candidates are in the merit list download
- Check the merit list of grade score is not empty
## Risk - how likely is this to impact other areas?
🟢 No risk - this is a self-contained piece of work

## Additional context
Include screen grabs, video demo, notes etc.

## Related permissions
Have permissions been considered for this functionality?
- No permission changes required
- Permissions have been added / updated. Details:

---
PREVIEW:DEVELOP
_can be OFF, DEVELOP or STAGING_

### CODE REVIEW

**Review by nickaddy — APPROVED** [review]
Looks good, but let's test it on Live

File: src/helpers/meritListHelper.js [hunk 1]
```diff
@@ -127,7 +130,10 @@ function scores(task, scoreType, exerciseDiversity) {
 
   // group scores
   const scoreMap = {};
-  task.finalScores.forEach(scoreData => { // id | panelId | ref | score | scoreSheet
+  console.log('task.finalScores', task.finalScores);
+  console.log('scoreType', scoreType);
```
Comment (warrensearle) [inline src/helpers/meritListHelper.js:134]: Please could you remove / comment these out?

File: src/helpers/meritListHelper.js [hunk 2]
```diff
@@ -196,6 +202,7 @@ function scores(task, scoreType, exerciseDiversity) {
   });
 
   // add outcome stats
+  console.log('scoreMap', scoreMap);
```
Comment (warrensearle) [inline src/helpers/meritListHelper.js:205]: ...and this one

File: src/views/Exercise/Tasks/Task/Finalised/List.vue [hunk 3]
```diff
@@ -372,6 +374,15 @@ export default {
       }
       return 'Type any part of reference number';
     },
+    takenTestScores() {
+      if (this.scoreType === 'zScore') {
+        return this.scores;
+      } else if (this.scoreType === 'gradeScore') {
+        return this.scores.filter(score => !_isEmpty(score.score) );
+      } else {
+        return this.scores.filter(score => score.score > 0);
```
Comment (warrensearle) [inline src/views/Exercise/Tasks/Task/Finalised/List.vue:383]: In theory I guess someone could get every question wrong and so have a score of 0... but they have actually taken the test. Does that mean this code/logic needs amending?

**Review by warrensearle — CHANGES_REQUESTED** [review]
Couple of tweaks please @KoWeiJAC 😄

File: src/views/Exercise/Tasks/Task/Finalised/List.vue (hunk 3 above)
Comment (KoWeiJAC) [reply src/views/Exercise/Tasks/Task/Finalised/List.vue:383]: You're right, if someone taken tests but the score is 0, will not appear in the merit list.
The line is made for accommodation of existing QT API behaviour, when creating score sheet, DP will call QT API to fetch scores, both 0 and not taken will have empty response from QT. So, we can't separate them at the moment.
I discussed with Nick about the issue, we couldn't update QT at that time, and the case would be rare,
so we can consider `0 score` as the same as `not taken` and not showing in the merit list.

For not showing `not taken `candidate in the merit list, we still need this line.
But, I think we can add a comment on it and create a ticket for this potential issue.

**Review by warrensearle — APPROVED** [review]
